<?php

namespace Database\Seeders;

use App\Models\CiType;
use App\Models\ConfigurationItem;
use App\Models\Organization;
use App\Models\Website;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class WebsiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Create a Default CI to bypass nullable restriction
        $ciType = CiType::first();
        $org = Organization::first();

        $defaultCi = ConfigurationItem::firstOrCreate(
            ['name' => 'General Website Server'],
            [
                'ci_code' => 'SRV-GEN-001',
                'ci_type_id' => $ciType ? $ciType->id : 1,
                'organization_id' => $org ? $org->id : 1,
                'environment' => 'production',
                'status' => 'active',
                'criticality' => 'medium',
                'description' => 'Default CI for websites imported from seeder',
            ]
        );

        // 2. The array of websites provided by User
        $websites = [
            ['url' => 'https://ciamiskab.go.id', 'name' => 'ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://situ.ciamiskab.go.id', 'name' => 'situ.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://esakip.ciamiskab.go.id', 'name' => 'esakip.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://data.ciamiskab.go.id', 'name' => 'data.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://pullahta.ciamiskab.go.id', 'name' => 'pullahta.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'http://silancar.ciamiskab.go.id/', 'name' => 'silancar.ciamiskab.go.id', 'author' => 'Disdukcapil'],
            ['url' => 'https://atcs.ciamiskab.go.id', 'name' => 'atcs.ciamiskab.go.id', 'author' => 'Dinas Perhubungan'],
            ['url' => 'https://asn.ciamiskab.go.id', 'name' => 'asn.ciamiskab.go.id', 'author' => 'BKPSDM'],
            ['url' => 'https://simpeg3.ciamiskab.go.id', 'name' => 'simpeg3.ciamiskab.go.id', 'author' => 'BKPSDM'],
            ['url' => 'https://talenta.ciamiskab.go.id', 'name' => 'talenta.ciamiskab.go.id', 'author' => 'BKPSDM'],
            ['url' => 'https://sibangpeci.ciamiskab.go.id', 'name' => 'sibangpeci.ciamiskab.go.id', 'author' => 'BKPSDM'],
            ['url' => 'https://threec.ciamiskab.go.id', 'name' => 'threec.ciamiskab.go.id', 'author' => 'Dinas PPKBP3A'],
            ['url' => 'https://jdih.ciamiskab.go.id', 'name' => 'jdih.ciamiskab.go.id', 'author' => 'Sekretariat Daerah'],
            ['url' => 'https://simanis.ciamiskab.go.id', 'name' => 'simanis.ciamiskab.go.id', 'author' => 'Dinas PMPTSP'],
            ['url' => 'https://galuhvirtual.ciamiskab.go.id', 'name' => 'galuhvirtual.ciamiskab.go.id', 'author' => 'Dinas Pariwisata'],
            ['url' => 'https://simungil.ciamiskab.go.id/', 'name' => 'simungil.ciamiskab.go.id', 'author' => 'Badan Kesatuan Bangsa dan Politik'],
            ['url' => 'https://ukpbj.ciamiskab.go.id', 'name' => 'ukpbj.ciamiskab.go.id', 'author' => 'Sekretariat Daerah'],
            ['url' => 'https://siskacampernik.ciamiskab.go.id', 'name' => 'siskacampernik.ciamiskab.go.id', 'author' => 'Pemkab Ciamis'],
            ['url' => 'https://ppid.ciamiskab.go.id', 'name' => 'ppid.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://app-bapenda.ciamiskab.go.id', 'name' => 'app-bapenda.ciamiskab.go.id', 'author' => 'Badan Pendapatan Daerah'],
            ['url' => 'https://investasi.ciamiskab.go.id', 'name' => 'investasi.ciamiskab.go.id', 'author' => 'Dinas PMPTSP'],
            ['url' => 'https://sijagal.ciamiskab.go.id', 'name' => 'sijagal.ciamiskab.go.id', 'author' => 'Dinas PRKPLH'],
            ['url' => 'http://esign-cp.ciamiskab.go.id', 'name' => 'esign-cp.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://sasakgaluh.ciamiskab.go.id', 'name' => 'sasakgaluh.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://portal-media.ciamiskab.go.id', 'name' => 'portal-media.ciamiskab.go.id', 'author' => 'Pemkab Ciamis'],
            ['url' => 'https://setda.ciamiskab.go.id', 'name' => 'setda.ciamiskab.go.id', 'author' => 'Sekretariat Daerah'],
            ['url' => 'https://setdprd.ciamiskab.go.id', 'name' => 'setdprd.ciamiskab.go.id', 'author' => 'Sekretariat Dprd'],
            ['url' => 'https://inspektorat.ciamiskab.go.id', 'name' => 'inspektorat.ciamiskab.go.id', 'author' => 'Inspektorat'],
            ['url' => 'https://bapperida.ciamiskab.go.id', 'name' => 'bapperida.ciamiskab.go.id', 'author' => 'Bapperida'],
            ['url' => 'https://bkpsdm.ciamiskab.go.id', 'name' => 'bkpsdm.ciamiskab.go.id', 'author' => 'BKPSDM'],
            ['url' => 'https://bpbd.ciamiskab.go.id', 'name' => 'bpbd.ciamiskab.go.id', 'author' => 'BPBD'],
            ['url' => 'https://dpmd.ciamiskab.go.id', 'name' => 'dpmd.ciamiskab.go.id', 'author' => 'Dinas PMD'],
            ['url' => 'https://dpkp.ciamiskab.go.id', 'name' => 'dpkp.ciamiskab.go.id', 'author' => 'Dinas Pertanian dan ketahanan Pangan'],
            ['url' => 'https://dinkes.ciamiskab.go.id', 'name' => 'dinkes.ciamiskab.go.id', 'author' => 'Dinas Kesehatan'],
            ['url' => 'https://dinsos.ciamiskab.go.id', 'name' => 'dinsos.ciamiskab.go.id', 'author' => 'Dinas Sosial'],
            ['url' => 'https://disbudpora.ciamiskab.go.id', 'name' => 'disbudpora.ciamiskab.go.id', 'author' => 'Disbudpora'],
            ['url' => 'https://disdik.ciamiskab.go.id', 'name' => 'disdik.ciamiskab.go.id', 'author' => 'Dinas Pendidikan'],
            ['url' => 'https://diskominfo.ciamiskab.go.id', 'name' => 'diskominfo.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://dishub.ciamiskab.go.id', 'name' => 'dishub.ciamiskab.go.id', 'author' => 'Dinas Perhubungan'],
            ['url' => 'https://dprkplh.ciamiskab.go.id', 'name' => 'dprkplh.ciamiskab.go.id', 'author' => 'Dinas PRKPLH'],
            ['url' => 'https://disnakan.ciamiskab.go.id', 'name' => 'disnakan.ciamiskab.go.id', 'author' => 'Dinas Peternakan dan Perikanan'],
            ['url' => 'https://disnaker.ciamiskab.go.id', 'name' => 'disnaker.ciamiskab.go.id', 'author' => 'Dinas Tenaga Kerja'],
            ['url' => 'https://dkukmpp.ciamiskab.go.id/', 'name' => 'dkukmpp.ciamiskab.go.id', 'author' => 'Dinas KUKMP'],
            ['url' => 'https://dpmptsp.ciamiskab.go.id', 'name' => 'dpmptsp.ciamiskab.go.id', 'author' => 'Dinas PMPTSP'],
            ['url' => 'https://dputrp.ciamiskab.go.id/', 'name' => 'dputrp.ciamiskab.go.id', 'author' => 'Dinas PUPRP'],
            ['url' => 'https://kesbangpol.ciamiskab.go.id', 'name' => 'kesbangpol.ciamiskab.go.id', 'author' => 'Badan Kesatuan Bangsa dan Politik'],
            ['url' => 'https://satpolpp.ciamiskab.go.id', 'name' => 'satpolpp.ciamiskab.go.id', 'author' => 'Satuan Polisi Pamong Praja'],
            ['url' => 'https://dispusip.ciamiskab.go.id', 'name' => 'dispusip.ciamiskab.go.id', 'author' => 'Dinas Perpustakaan dan Kearsipan'],
            ['url' => 'https://dppkbpppa.ciamiskab.go.id', 'name' => 'dppkbpppa.ciamiskab.go.id', 'author' => 'Dinas PPKBP3A'],
            ['url' => 'https://dispar.ciamiskab.go.id', 'name' => 'dispar.ciamiskab.go.id', 'author' => 'Dinas Pariwisata'],
            ['url' => 'https://disdukcapil.ciamiskab.go.id', 'name' => 'disdukcapil.ciamiskab.go.id', 'author' => 'Disdukcapil'],
            ['url' => 'https://bpkd.ciamiskab.go.id', 'name' => 'bpkd.ciamiskab.go.id', 'author' => 'Badan Pengelolaan Keuangan Daerah'],
            ['url' => 'https://rsud.ciamiskab.go.id', 'name' => 'rsud.ciamiskab.go.id', 'author' => 'Rumah Sakit Umum Daerah'],
            ['url' => 'https://pkm-ciamis.ciamiskab.go.id', 'name' => 'pkm-ciamis.ciamiskab.go.id', 'author' => 'PUSKESMAS CIAMIS'],
            ['url' => 'https://pkm-imbanagara.ciamiskab.go.id', 'name' => 'pkm-imbanagara.ciamiskab.go.id', 'author' => 'PUSKESMAS IMBANAGARA'],
            ['url' => 'https://pkm-banjarsari.ciamiskab.go.id', 'name' => 'pkm-banjarsari.ciamiskab.go.id', 'author' => 'PUSKESMAS BANJARSARI'],
            ['url' => 'https://pkm-ciulu.ciamiskab.go.id', 'name' => 'pkm-ciulu.ciamiskab.go.id', 'author' => 'PUSKESMAS CIULU'],
            ['url' => 'https://pkm-baregbeg.ciamiskab.go.id', 'name' => 'pkm-baregbeg.ciamiskab.go.id', 'author' => 'PUSKESMAS BAREGBEG'],
            ['url' => 'https://pkm-cidolog.ciamiskab.go.id', 'name' => 'pkm-cidolog.ciamiskab.go.id', 'author' => 'PUSKESMAS CIDOLOG'],
            ['url' => 'https://pkm-cipaku.ciamiskab.go.id', 'name' => 'pkm-cipaku.ciamiskab.go.id', 'author' => 'PUSKESMAS CIPAKU'],
            ['url' => 'https://pkm-cieurih.ciamiskab.go.id', 'name' => 'pkm-cieurih.ciamiskab.go.id', 'author' => 'PUSKESMAS CIEURIH'],
            ['url' => 'https://pkm-cigayam.ciamiskab.go.id', 'name' => 'pkm-cigayam.ciamiskab.go.id', 'author' => 'PUSKESMAS CIGAYAM'],
            ['url' => 'https://pkm-cihaurbeuti.ciamiskab.go.id', 'name' => 'pkm-cihaurbeuti.ciamiskab.go.id', 'author' => 'PUSKESMAS CIHAURBEUTI'],
            ['url' => 'https://pkm-sukamulya.ciamiskab.go.id', 'name' => 'pkm-sukamulya.ciamiskab.go.id', 'author' => 'PUSKESMAS SUKAMULYA'],
            ['url' => 'https://pkm-cijeungjing.ciamiskab.go.id', 'name' => 'pkm-cijeungjing.ciamiskab.go.id', 'author' => 'PUSKESMAS CIJEUNGJING'],
            ['url' => 'https://pkm-handapherang.ciamiskab.go.id', 'name' => 'pkm-handapherang.ciamiskab.go.id', 'author' => 'PUSKESMAS HANDAPHERANG'],
            ['url' => 'https://pkm-cikoneng.ciamiskab.go.id', 'name' => 'pkm-cikoneng.ciamiskab.go.id', 'author' => 'PUSKESMAS CIKONENG'],
            ['url' => 'https://pkm-cimaragas.ciamiskab.go.id', 'name' => 'pkm-cimaragas.ciamiskab.go.id', 'author' => 'PUSKESMAS CIMARAGAS'],
            ['url' => 'https://pkm-cisaga.ciamiskab.go.id', 'name' => 'pkm-cisaga.ciamiskab.go.id', 'author' => 'PUSKESMAS CISAGA'],
            ['url' => 'https://pkm-jatinagara.ciamiskab.go.id', 'name' => 'pkm-jatinagara.ciamiskab.go.id', 'author' => 'PUSKESMAS JATINAGARA'],
            ['url' => 'https://pkm-kawali.ciamiskab.go.id', 'name' => 'pkm-kawali.ciamiskab.go.id', 'author' => 'PUSKESMAS KAWALI'],
            ['url' => 'https://pkm-kawalimukti.ciamiskab.go.id', 'name' => 'pkm-kawalimukti.ciamiskab.go.id', 'author' => 'PUSKESMAS KAWALIMUKTI'],
            ['url' => 'https://pkm-kertahayu.ciamiskab.go.id', 'name' => 'pkm-kertahayu.ciamiskab.go.id', 'author' => 'PUSKESMAS KERTAHAYU'],
            ['url' => 'https://pkm-lakbok.ciamiskab.go.id', 'name' => 'pkm-lakbok.ciamiskab.go.id', 'author' => 'PUSKESMAS LAKBOK'],
            ['url' => 'https://pkm-lumbung.ciamiskab.go.id', 'name' => 'pkm-lumbung.ciamiskab.go.id', 'author' => 'PUSKESMAS LUMBUNG'],
            ['url' => 'https://pkm-pamarican.ciamiskab.go.id', 'name' => 'pkm-pamarican.ciamiskab.go.id', 'author' => 'PUSKESMAS PAMARICAN'],
            ['url' => 'https://pkm-panawangan.ciamiskab.go.id', 'name' => 'pkm-panawangan.ciamiskab.go.id', 'author' => 'PUSKESMAS PANAWANGAN'],
            ['url' => 'https://pkm-gardujaya.ciamiskab.go.id', 'name' => 'pkm-gardujaya.ciamiskab.go.id', 'author' => 'PUSKESMAS GARDUJAYA'],
            ['url' => 'https://pkm-panjalu.ciamiskab.go.id', 'name' => 'pkm-panjalu.ciamiskab.go.id', 'author' => 'PUSKESMAS PANJALU'],
            ['url' => 'https://pkm-panumbangan.ciamiskab.go.id', 'name' => 'pkm-panumbangan.ciamiskab.go.id', 'author' => 'PUSKESMAS PANUMBANGAN'],
            ['url' => 'https://pkm-payungsari.ciamiskab.go.id', 'name' => 'pkm-payungsari.ciamiskab.go.id', 'author' => 'PUSKESMAS PAYUNGSARI'],
            ['url' => 'https://pkm-purwadadi.ciamiskab.go.id', 'name' => 'pkm-purwadadi.ciamiskab.go.id', 'author' => 'PUSKESMAS PURWADADI'],
            ['url' => 'https://pkm-sidaharja.ciamiskab.go.id', 'name' => 'pkm-sidaharja.ciamiskab.go.id', 'author' => 'PUSKESMAS SIDAHARJA'],
            ['url' => 'https://pkm-rajadesa.ciamiskab.go.id', 'name' => 'pkm-rajadesa.ciamiskab.go.id', 'author' => 'PUSKESMAS RAJADESA'],
            ['url' => 'https://pkm-rancah.ciamiskab.go.id', 'name' => 'pkm-rancah.ciamiskab.go.id', 'author' => 'PUSKESMAS RANCAH'],
            ['url' => 'https://pkm-sadananya.ciamiskab.go.id', 'name' => 'pkm-sadananya.ciamiskab.go.id', 'author' => 'PUSKESMAS SADANANYA'],
            ['url' => 'https://pkm-sindangkasih.ciamiskab.go.id', 'name' => 'pkm-sindangkasih.ciamiskab.go.id', 'author' => 'PUSKESMAS SINDANGKASIH'],
            ['url' => 'https://pkm-sukadana.ciamiskab.go.id', 'name' => 'pkm-sukadana.ciamiskab.go.id', 'author' => 'PUSKESMAS SUKADANA'],
            ['url' => 'https://pkm-sukamantri.ciamiskab.go.id', 'name' => 'pkm-sukamantri.ciamiskab.go.id', 'author' => 'PUSKESMAS SUKAMANTRI'],
            ['url' => 'https://pkm-tambaksari.ciamiskab.go.id', 'name' => 'pkm-tambaksari.ciamiskab.go.id', 'author' => 'PUSKESMAS TAMBAKSARI'],
            ['url' => 'https://kecamatan-ciamis.ciamiskab.go.id', 'name' => 'kecamatan-ciamis.ciamiskab.go.id', 'author' => 'Kecamatan Ciamis'],
            ['url' => 'https://kecamatan-baregbeg.ciamiskab.go.id', 'name' => 'kecamatan-baregbeg.ciamiskab.go.id', 'author' => 'Kecamatan Baregbeg'],
            ['url' => 'https://kecamatan-cijeungjing.ciamiskab.go.id', 'name' => 'kecamatan-cijeungjing.ciamiskab.go.id', 'author' => 'Kecamatan Cijeungjing'],
            ['url' => 'https://kecamatan-sadananya.ciamiskab.go.id', 'name' => 'kecamatan-sadananya.ciamiskab.go.id', 'author' => 'Kecamatan Sadananya'],
            ['url' => 'https://kecamatan-cikoneng.ciamiskab.go.id', 'name' => 'kecamatan-cikoneng.ciamiskab.go.id', 'author' => 'Kecamatan Cikoneng'],
            ['url' => 'https://kecamatan-sukadana.ciamiskab.go.id', 'name' => 'kecamatan-sukadana.ciamiskab.go.id', 'author' => 'Kecamatan Sukadana'],
            ['url' => 'https://kecamatan-sindangkasih.ciamiskab.go.id', 'name' => 'kecamatan-sindangkasih.ciamiskab.go.id', 'author' => 'Kecamatan Sindangkasih'],
            ['url' => 'https://kecamatan-cisaga.ciamiskab.go.id', 'name' => 'kecamatan-cisaga.ciamiskab.go.id', 'author' => 'Kecamatan Cisaga'],
            ['url' => 'https://kecamatan-cipaku.ciamiskab.go.id', 'name' => 'kecamatan-cipaku.ciamiskab.go.id', 'author' => 'Kecamatan Cipaku'],
            ['url' => 'https://kecamatan-cimaragas.ciamiskab.go.id', 'name' => 'kecamatan-cimaragas.ciamiskab.go.id', 'author' => 'Kecamatan Cimaragas'],
            ['url' => 'https://kecamatan-cihaurbeuti.ciamiskab.go.id', 'name' => 'kecamatan-cihaurbeuti.ciamiskab.go.id', 'author' => 'Kecamatan Cihaurbeuti'],
            ['url' => 'https://kecamatan-cidolog.ciamiskab.go.id', 'name' => 'kecamatan-cidolog.ciamiskab.go.id', 'author' => 'Kecamatan Cidolog'],
            ['url' => 'https://kecamatan-kawali.ciamiskab.go.id', 'name' => 'kecamatan-kawali.ciamiskab.go.id', 'author' => 'Kecamatan Kawali'],
            ['url' => 'https://kecamatan-jatinagara.ciamiskab.go.id', 'name' => 'kecamatan-jatinagara.ciamiskab.go.id', 'author' => 'Kecamatan Jatinagara'],
            ['url' => 'https://kecamatan-rancah.ciamiskab.go.id', 'name' => 'kecamatan-rancah.ciamiskab.go.id', 'author' => 'Kecamatan Rancah'],
            ['url' => 'https://kecamatan-lumbung.ciamiskab.go.id', 'name' => 'kecamatan-lumbung.ciamiskab.go.id', 'author' => 'Kecamatan Lumbung'],
            ['url' => 'https://kecamatan-rajadesa.ciamiskab.go.id', 'name' => 'kecamatan-rajadesa.ciamiskab.go.id', 'author' => 'Kecamatan Rajadesa'],
            ['url' => 'https://kecamatan-panawangan.ciamiskab.go.id', 'name' => 'kecamatan-panawangan.ciamiskab.go.id', 'author' => 'Kecamatan Panawangan'],
            ['url' => 'https://kecamatan-panumbangan.ciamiskab.go.id', 'name' => 'kecamatan-panumbangan.ciamiskab.go.id', 'author' => 'Kecamatan Panumbangan'],
            ['url' => 'https://kecamatan-panjalu.ciamiskab.go.id', 'name' => 'kecamatan-panjalu.ciamiskab.go.id', 'author' => 'Kecamatan Panjalu'],
            ['url' => 'https://kecamatan-lakbok.ciamiskab.go.id', 'name' => 'kecamatan-lakbok.ciamiskab.go.id', 'author' => 'Kecamatan Lakbok'],
            ['url' => 'https://kecamatan-banjarsari.ciamiskab.go.id', 'name' => 'kecamatan-banjarsari.ciamiskab.go.id', 'author' => 'Kecamatan Banjarsari'],
            ['url' => 'https://kecamatan-pamarican.ciamiskab.go.id', 'name' => 'kecamatan-pamarican.ciamiskab.go.id', 'author' => 'Kecamatan Pamarican'],
            ['url' => 'https://kecamatan-sukamantri.ciamiskab.go.id', 'name' => 'kecamatan-sukamantri.ciamiskab.go.id', 'author' => 'Kecamatan Sukamantri'],
            ['url' => 'https://kecamatan-tambaksari.ciamiskab.go.id', 'name' => 'kecamatan-tambaksari.ciamiskab.go.id', 'author' => 'Kecamatan Tambaksari'],
            ['url' => 'https://kecamatan-banjaranyar.ciamiskab.go.id', 'name' => 'kecamatan-banjaranyar.ciamiskab.go.id', 'author' => 'Kecamatan Banjaranyar'],
            ['url' => 'https://kecamatan-purwadadi.ciamiskab.go.id', 'name' => 'kecamatan-purwadadi.ciamiskab.go.id', 'author' => 'Kecamatan Purwadadi'],
            ['url' => 'https://kelurahan-ciamis.ciamiskab.go.id', 'name' => 'kelurahan-ciamis.ciamiskab.go.id', 'author' => 'KELURAHAN CIAMIS'],
            ['url' => 'https://kelurahan-maleber.ciamiskab.go.id', 'name' => 'kelurahan-maleber.ciamiskab.go.id', 'author' => 'KELURAHAN MALEBER'],
            ['url' => 'https://kelurahan-sindangrasa.ciamiskab.go.id', 'name' => 'kelurahan-sindangrasa.ciamiskab.go.id', 'author' => 'KELURAHAN SINDANGRASA'],
            ['url' => 'https://kelurahan-kertasari.ciamiskab.go.id', 'name' => 'kelurahan-kertasari.ciamiskab.go.id', 'author' => 'KELURAHAN KERTASARI'],
            ['url' => 'https://kelurahan-linggasari.ciamiskab.go.id', 'name' => 'kelurahan-linggasari.ciamiskab.go.id', 'author' => 'KELURAHAN LINGGASARI'],
            ['url' => 'https://kelurahan-benteng.ciamiskab.go.id', 'name' => 'kelurahan-benteng.ciamiskab.go.id', 'author' => 'KELURAHAN BENTENG'],
            ['url' => 'https://kelurahan-cigembor.ciamiskab.go.id', 'name' => 'kelurahan-cigembor.ciamiskab.go.id', 'author' => 'KELURAHAN CIGEMBOR'],
            ['url' => 'https://pawindan.desa.id', 'name' => 'pawindan.desa.id', 'author' => 'PAWINDAN'],
            ['url' => 'https://cisadap.desa.id', 'name' => 'cisadap.desa.id', 'author' => 'CISADAP'],
            ['url' => 'https://panaragan.desa.id', 'name' => 'panaragan.desa.id', 'author' => 'PANARAGAN'],
            ['url' => 'https://nasol.desa.id', 'name' => 'nasol.desa.id', 'author' => 'NASOL'],
            ['url' => 'https://gegempalan.desa.id', 'name' => 'gegempalan.desa.id', 'author' => 'GEGEMPALAN'],
            ['url' => 'https://cihalarang.desa.id', 'name' => 'cihalarang.desa.id', 'author' => 'CIHALARANG'],
            ['url' => 'https://karangkamulyan.desa.id', 'name' => 'karangkamulyan.desa.id', 'author' => 'KARANGKAMULYAN'],
            ['url' => 'https://kertabumi.desa.id', 'name' => 'kertabumi.desa.id', 'author' => 'KERTABUMI'],
            ['url' => 'https://cijeungjing.desa.id', 'name' => 'cijeungjing.desa.id', 'author' => 'CIJEUNGJING'],
            ['url' => 'https://pamalayan-ciamis.desa.id', 'name' => 'pamalayan-ciamis.desa.id', 'author' => 'PAMALAYAN-CIAMIS'],
            ['url' => 'https://utama.desa.id', 'name' => 'utama.desa.id', 'author' => 'UTAMA'],
            ['url' => 'https://kertaharja-cijeungjing.desa.id', 'name' => 'kertaharja-cijeungjing.desa.id', 'author' => 'KERTAHARJA-CIJEUNGJING'],
            ['url' => 'https://karanganyar-cijeungjing.desa.id', 'name' => 'karanganyar-cijeungjing.desa.id', 'author' => 'KARANGANYAR-CIJEUNGJING'],
            ['url' => 'https://cidolog.desa.id', 'name' => 'cidolog.desa.id', 'author' => 'CIDOLOG'],
            ['url' => 'https://janggala.desa.id', 'name' => 'janggala.desa.id', 'author' => 'JANGGALA'],
            ['url' => 'https://hegarmanah-cidolog.desa.id', 'name' => 'hegarmanah-cidolog.desa.id', 'author' => 'HEGARMANAH-CIDOLOG'],
            ['url' => 'https://jelegong-cidolog.desa.id', 'name' => 'jelegong-cidolog.desa.id', 'author' => 'JELEGONG-CIDOLOG'],
            ['url' => 'https://ciparay-cidolog.desa.id', 'name' => 'ciparay-cidolog.desa.id', 'author' => 'CIPARAY-CIDOLOG'],
            ['url' => 'https://sukasari-cidolog.desa.id', 'name' => 'sukasari-cidolog.desa.id', 'author' => 'SUKASARI-CIDOLOG'],
            ['url' => 'https://sukamulya-chb.desa.id', 'name' => 'sukamulya-chb.desa.id', 'author' => 'SUKAMULYA-CHB'],
            ['url' => 'https://sukahurip-cihaurbeuti.desa.id', 'name' => 'sukahurip-cihaurbeuti.desa.id', 'author' => 'SUKAHURIP-CIHAURBEUTI'],
            ['url' => 'https://sukamaju-cihaurbeuti.desa.id', 'name' => 'sukamaju-cihaurbeuti.desa.id', 'author' => 'SUKAMAJU-CIHAURBEUTI'],
            ['url' => 'https://sukasetia-cihaurbeuti.desa.id', 'name' => 'sukasetia-cihaurbeuti.desa.id', 'author' => 'SUKASETIA-CIHAURBEUTI'],
            ['url' => 'https://sumberjaya-cihaurbeuti.desa.id', 'name' => 'sumberjaya-cihaurbeuti.desa.id', 'author' => 'SUMBERJAYA-CIHAURBEUTI'],
            ['url' => 'https://cihaurbeuti-cihaurbeuti.desa.id', 'name' => 'cihaurbeuti-cihaurbeuti.desa.id', 'author' => 'CIHAURBEUTI-CIHAURBEUTI'],
            ['url' => 'https://pasirtamiang.desa.id', 'name' => 'pasirtamiang.desa.id', 'author' => 'PASIRTAMIANG'],
            ['url' => 'https://padamulya-cihaurbeuti.desa.id', 'name' => 'padamulya-cihaurbeuti.desa.id', 'author' => 'PADAMULYA-CIHAURBEUTI'],
            ['url' => 'https://pamokolan.desa.id', 'name' => 'pamokolan.desa.id', 'author' => 'PAMOKOLAN'],
            ['url' => 'https://sukahaji-cihaurbeuti.desa.id', 'name' => 'sukahaji-cihaurbeuti.desa.id', 'author' => 'SUKAHAJI-CIHAURBEUTI'],
            ['url' => 'https://medanglayang.desa.id', 'name' => 'medanglayang.desa.id', 'author' => 'MEDANGLAYANG'],
            ['url' => 'https://panumbangan.desa.id', 'name' => 'panumbangan.desa.id', 'author' => 'PANUMBANGAN'],
            ['url' => 'https://golat.desa.id', 'name' => 'golat.desa.id', 'author' => 'GOLAT'],
            ['url' => 'https://sindangherang.desa.id', 'name' => 'sindangherang.desa.id', 'author' => 'SINDANGHERANG'],
            ['url' => 'https://banjarangsana.desa.id', 'name' => 'banjarangsana.desa.id', 'author' => 'BANJARANGSANA'],
            ['url' => 'https://payungagung.desa.id', 'name' => 'payungagung.desa.id', 'author' => 'PAYUNGAGUNG'],
            ['url' => 'https://tanjungmulya.desa.id', 'name' => 'tanjungmulya.desa.id', 'author' => 'TANJUNGMULYA'],
            ['url' => 'https://payungsari.desa.id', 'name' => 'payungsari.desa.id', 'author' => 'PAYUNGSARI'],
            ['url' => 'https://jayagiri-pnb.desa.id', 'name' => 'jayagiri-pnb.desa.id', 'author' => 'JAYAGIRI-PNB'],
            ['url' => 'https://kertaraharja.desa.id', 'name' => 'kertaraharja.desa.id', 'author' => 'KERTARAHARJA'],
            ['url' => 'https://sindangmukti.desa.id', 'name' => 'sindangmukti.desa.id', 'author' => 'SINDANGMUKTI'],
            ['url' => 'https://sindangbarang.desa.id', 'name' => 'sindangbarang.desa.id', 'author' => 'SINDANGBARANG'],
            ['url' => 'https://buanamekar.desa.id', 'name' => 'buanamekar.desa.id', 'author' => 'BUANAMEKAR'],
            ['url' => 'https://panjalu.desa.id', 'name' => 'panjalu.desa.id', 'author' => 'PANJALU'],
            ['url' => 'https://ciomas.desa.id', 'name' => 'ciomas.desa.id', 'author' => 'CIOMAS'],
            ['url' => 'https://sandingtaman.desa.id', 'name' => 'sandingtaman.desa.id', 'author' => 'SANDINGTAMAN'],
            ['url' => 'https://maparah.desa.id', 'name' => 'maparah.desa.id', 'author' => 'MAPARAH'],
            ['url' => 'https://bahara.desa.id', 'name' => 'bahara.desa.id', 'author' => 'BAHARA'],
            ['url' => 'https://hujungtiwu.desa.id', 'name' => 'hujungtiwu.desa.id', 'author' => 'HUJUNGTIWU'],
            ['url' => 'https://mandalare.desa.id', 'name' => 'mandalare.desa.id', 'author' => 'MANDALARE'],
            ['url' => 'https://kawali.desa.id', 'name' => 'kawali.desa.id', 'author' => 'KAWALI'],
            ['url' => 'https://talagasari-kawali.desa.id', 'name' => 'talagasari-kawali.desa.id', 'author' => 'TALAGASARI-KAWALI'],
            ['url' => 'https://karangpawitan.desa.id', 'name' => 'karangpawitan.desa.id', 'author' => 'KARANGPAWITAN'],
            ['url' => 'https://winduraja.desa.id', 'name' => 'winduraja.desa.id', 'author' => 'WINDURAJA'],
            ['url' => 'https://margamulya-kawali.desa.id', 'name' => 'margamulya-kawali.desa.id', 'author' => 'MARGAMULYA-KAWALI'],
            ['url' => 'https://purwasari-kawali.desa.id', 'name' => 'purwasari-kawali.desa.id', 'author' => 'PURWASARI-KAWALI'],
            ['url' => 'https://sindangsari-kawali.desa.id', 'name' => 'sindangsari-kawali.desa.id', 'author' => 'SINDANGSARI-KAWALI'],
            ['url' => 'https://kawalimukti.desa.id', 'name' => 'kawalimukti.desa.id', 'author' => 'KAWALIMUKTI'],
            ['url' => 'https://selasari-kawali.desa.id', 'name' => 'selasari-kawali.desa.id', 'author' => 'SELASARI-KAWALI'],
            ['url' => 'https://panawangan.desa.id', 'name' => 'panawangan.desa.id', 'author' => 'PANAWANGAN'],
            ['url' => 'https://sagalaherang.desa.id', 'name' => 'sagalaherang.desa.id', 'author' => 'SAGALAHERANG'],
            ['url' => 'https://nagarapageuh.desa.id', 'name' => 'nagarapageuh.desa.id', 'author' => 'NAGARAPAGEUH'],
            ['url' => 'https://nagarajati.desa.id', 'name' => 'nagarajati.desa.id', 'author' => 'NAGARAJATI'],
            ['url' => 'https://nagarajaya.desa.id', 'name' => 'nagarajaya.desa.id', 'author' => 'NAGARAJAYA'],
            ['url' => 'https://kertayasa.desa.id', 'name' => 'kertayasa.desa.id', 'author' => 'KERTAYASA'],
            ['url' => 'https://indragiri-panawangan.desa.id', 'name' => 'indragiri-panawangan.desa.id', 'author' => 'INDRAGIRI-PANAWANGAN'],
            ['url' => 'https://cinyasag-panawangan.desa.id', 'name' => 'cinyasag-panawangan.desa.id', 'author' => 'CINYASAG-PANAWANGAN'],
            ['url' => 'https://sadapaingan.desa.id', 'name' => 'sadapaingan.desa.id', 'author' => 'SADAPAINGAN'],
            ['url' => 'https://jagabaya-panawangan.desa.id', 'name' => 'jagabaya-panawangan.desa.id', 'author' => 'JAGABAYA-PANAWANGAN'],
            ['url' => 'https://gardujaya.desa.id', 'name' => 'gardujaya.desa.id', 'author' => 'GARDUJAYA'],
            ['url' => 'https://karangpaningal-panawangan.desa.id', 'name' => 'karangpaningal-panawangan.desa.id', 'author' => 'KARANGPANINGAL-PANAWANGAN'],
            ['url' => 'https://bangunjaya-panawangan.desa.id', 'name' => 'bangunjaya-panawangan.desa.id', 'author' => 'BANGUNJAYA-PANAWANGAN'],
            ['url' => 'https://girilaya.desa.id', 'name' => 'girilaya.desa.id', 'author' => 'GIRILAYA'],
            ['url' => 'https://kertajaya-panawangan.desa.id', 'name' => 'kertajaya-panawangan.desa.id', 'author' => 'KERTAJAYA-PANAWANGAN'],
            ['url' => 'https://nagarawangi-panawangan.desa.id', 'name' => 'nagarawangi-panawangan.desa.id', 'author' => 'NAGARAWANGI-PANAWANGAN'],
            ['url' => 'https://mekarbuana.desa.id', 'name' => 'mekarbuana.desa.id', 'author' => 'MEKARBUANA'],
            ['url' => 'https://natanegara.desa.id', 'name' => 'natanegara.desa.id', 'author' => 'NATANEGARA'],
            ['url' => 'https://buniseuri.desa.id', 'name' => 'buniseuri.desa.id', 'author' => 'BUNISEURI'],
            ['url' => 'https://selacai.desa.id', 'name' => 'selacai.desa.id', 'author' => 'SELACAI'],
            ['url' => 'https://jalatrang-cipaku.desa.id', 'name' => 'jalatrang-cipaku.desa.id', 'author' => 'JALATRANG-CIPAKU'],
            ['url' => 'https://cipaku-ciamis.desa.id', 'name' => 'cipaku-ciamis.desa.id', 'author' => 'CIPAKU-CIAMIS'],
            ['url' => 'https://cieurih-ciamis.desa.id', 'name' => 'cieurih-ciamis.desa.id', 'author' => 'CIEURIH-CIAMIS'],
            ['url' => 'https://pusakasari.desa.id', 'name' => 'pusakasari.desa.id', 'author' => 'PUSAKASARI'],
            ['url' => 'https://bangbayang-cipaku.desa.id', 'name' => 'bangbayang-cipaku.desa.id', 'author' => 'BANGBAYANG-CIPAKU'],
            ['url' => 'https://selamanik.desa.id', 'name' => 'selamanik.desa.id', 'author' => 'SELAMANIK'],
            ['url' => 'https://ciakar.desa.id', 'name' => 'ciakar.desa.id', 'author' => 'CIAKAR'],
            ['url' => 'https://sukawening-cipaku.desa.id', 'name' => 'sukawening-cipaku.desa.id', 'author' => 'SUKAWENING-CIPAKU'],
            ['url' => 'https://jatinagara.desa.id', 'name' => 'jatinagara.desa.id', 'author' => 'JATINAGARA'],
            ['url' => 'https://sukanagara-jatinagara.desa.id', 'name' => 'sukanagara-jatinagara.desa.id', 'author' => 'SUKANAGARA-JATINAGARA'],
            ['url' => 'https://cintanagara.desa.id', 'name' => 'cintanagara.desa.id', 'author' => 'CINTANAGARA'],
            ['url' => 'https://dayeuhluhur.desa.id', 'name' => 'dayeuhluhur.desa.id', 'author' => 'DAYEUHLUHUR'],
            ['url' => 'https://mulyasari-jatinagara.desa.id', 'name' => 'mulyasari-jatinagara.desa.id', 'author' => 'MULYASARI-JATINAGARA'],
            ['url' => 'https://bayasari.desa.id', 'name' => 'bayasari.desa.id', 'author' => 'BAYASARI'],
            ['url' => 'https://rajadesa.desa.id', 'name' => 'rajadesa.desa.id', 'author' => 'RAJADESA'],
            ['url' => 'https://tanjungsukur.desa.id', 'name' => 'tanjungsukur.desa.id', 'author' => 'TANJUNGSUKUR'],
            ['url' => 'https://tanjungsari-rajadesa.desa.id', 'name' => 'tanjungsari-rajadesa.desa.id', 'author' => 'TANJUNGSARI-RAJADESA'],
            ['url' => 'https://tanjungjaya.desa.id', 'name' => 'tanjungjaya.desa.id', 'author' => 'TANJUNGJAYA'],
            ['url' => 'https://andapraja.desa.id', 'name' => 'andapraja.desa.id', 'author' => 'ANDAPRAJA'],
            ['url' => 'https://sukaharja-rajadesa.desa.id', 'name' => 'sukaharja-rajadesa.desa.id', 'author' => 'SUKAHARJA-RAJADESA'],
            ['url' => 'https://sukajaya-rajadesa.desa.id', 'name' => 'sukajaya-rajadesa.desa.id', 'author' => 'SUKAJAYA-RAJADESA'],
            ['url' => 'https://tigaherang.desa.id', 'name' => 'tigaherang.desa.id', 'author' => 'TIGAHERANG'],
            ['url' => 'https://sirnabaya.desa.id', 'name' => 'sirnabaya.desa.id', 'author' => 'SIRNABAYA'],
            ['url' => 'https://sirnajaya-rajadesa.desa.id', 'name' => 'sirnajaya-rajadesa.desa.id', 'author' => 'SIRNAJAYA-RAJADESA'],
            ['url' => 'https://purwaraja.desa.id', 'name' => 'purwaraja.desa.id', 'author' => 'PURWARAJA'],
            ['url' => 'https://sukadana-ciamis.desa.id', 'name' => 'sukadana-ciamis.desa.id', 'author' => 'SUKADANA-CIAMIS'],
            ['url' => 'https://salakaria.desa.id', 'name' => 'salakaria.desa.id', 'author' => 'SALAKARIA'],
            ['url' => 'https://margaharja.desa.id', 'name' => 'margaharja.desa.id', 'author' => 'MARGAHARJA'],
            ['url' => 'https://margajaya-sukadana.desa.id', 'name' => 'margajaya-sukadana.desa.id', 'author' => 'MARGAJAYA-SUKADANA'],
            ['url' => 'https://bunter.desa.id', 'name' => 'bunter.desa.id', 'author' => 'BUNTER'],
            ['url' => 'https://ciparigi.desa.id', 'name' => 'ciparigi.desa.id', 'author' => 'CIPARIGI'],
            ['url' => 'https://rancah.desa.id', 'name' => 'rancah.desa.id', 'author' => 'RANCAH'],
            ['url' => 'https://kiarapayung.desa.id', 'name' => 'kiarapayung.desa.id', 'author' => 'KIARAPAYUNG'],
            ['url' => 'https://cileungsir.desa.id', 'name' => 'cileungsir.desa.id', 'author' => 'CILEUNGSIR'],
            ['url' => 'https://cisontrol.desa.id', 'name' => 'cisontrol.desa.id', 'author' => 'CISONTROL'],
            ['url' => 'https://bojonggedang.desa.id', 'name' => 'bojonggedang.desa.id', 'author' => 'BOJONGGEDANG'],
            ['url' => 'https://karangpari.desa.id', 'name' => 'karangpari.desa.id', 'author' => 'KARANGPARI'],
            ['url' => 'https://dadiharja.desa.id', 'name' => 'dadiharja.desa.id', 'author' => 'DADIHARJA'],
            ['url' => 'https://giriharja.desa.id', 'name' => 'giriharja.desa.id', 'author' => 'GIRIHARJA'],
            ['url' => 'https://wangunsari-rancah.desa.id', 'name' => 'wangunsari-rancah.desa.id', 'author' => 'WANGUNSARI-RANCAH'],
            ['url' => 'https://situmandala.desa.id', 'name' => 'situmandala.desa.id', 'author' => 'SITUMANDALA'],
            ['url' => 'https://kawunglarang.desa.id', 'name' => 'kawunglarang.desa.id', 'author' => 'KAWUNGLARANG'],
            ['url' => 'https://patakaharja.desa.id', 'name' => 'patakaharja.desa.id', 'author' => 'PATAKAHARJA'],
            ['url' => 'https://tambaksari-tambaksari.desa.id', 'name' => 'tambaksari-tambaksari.desa.id', 'author' => 'TAMBAKSARI-TAMBAKSARI'],
            ['url' => 'https://mekarsari-tambaksari.desa.id', 'name' => 'mekarsari-tambaksari.desa.id', 'author' => 'MEKARSARI-TAMBAKSARI'],
            ['url' => 'https://kaso.desa.id', 'name' => 'kaso.desa.id', 'author' => 'KASO'],
            ['url' => 'https://kadupandak-tambaksari.desa.id', 'name' => 'kadupandak-tambaksari.desa.id', 'author' => 'KADUPANDAK-TAMBAKSARI'],
            ['url' => 'https://sukasari-tambaksari.desa.id', 'name' => 'sukasari-tambaksari.desa.id', 'author' => 'SUKASARI-TAMBAKSARI'],
            ['url' => 'https://karangpaningal-tambaksari.desa.id', 'name' => 'karangpaningal-tambaksari.desa.id', 'author' => 'KARANGPANINGAL-TAMBAKSARI'],
            ['url' => 'https://sidaharja-lakbok.desa.id', 'name' => 'sidaharja-lakbok.desa.id', 'author' => 'SIDAHARJA-LAKBOK'],
            ['url' => 'https://kertajaya-lakbok.desa.id', 'name' => 'kertajaya-lakbok.desa.id', 'author' => 'KERTAJAYA-LAKBOK'],
            ['url' => 'https://sukanagara-lakbok.desa.id', 'name' => 'sukanagara-lakbok.desa.id', 'author' => 'SUKANAGARA-LAKBOK'],
            ['url' => 'https://cintajaya.desa.id', 'name' => 'cintajaya.desa.id', 'author' => 'CINTAJAYA'],
            ['url' => 'https://cintaratu-lakbok.desa.id', 'name' => 'cintaratu-lakbok.desa.id', 'author' => 'CINTARATU-LAKBOK'],
            ['url' => 'https://sindangangin.desa.id', 'name' => 'sindangangin.desa.id', 'author' => 'SINDANGANGIN'],
            ['url' => 'https://tambakreja.desa.id', 'name' => 'tambakreja.desa.id', 'author' => 'TAMBAKREJA'],
            ['url' => 'https://baregbeg-lakbok.desa.id', 'name' => 'baregbeg-lakbok.desa.id', 'author' => 'BAREGBEG-LAKBOK'],
            ['url' => 'https://kalapasawit.desa.id', 'name' => 'kalapasawit.desa.id', 'author' => 'KALAPASAWIT'],
            ['url' => 'https://puloerang.desa.id', 'name' => 'puloerang.desa.id', 'author' => 'PULOERANG'],
            ['url' => 'https://kawasen.desa.id', 'name' => 'kawasen.desa.id', 'author' => 'KAWASEN'],
            ['url' => 'https://cicapar.desa.id', 'name' => 'cicapar.desa.id', 'author' => 'CICAPAR'],
            ['url' => 'https://cibadak-ciamis.desa.id', 'name' => 'cibadak-ciamis.desa.id', 'author' => 'CIBADAK-CIAMIS'],
            ['url' => 'https://banjarsari-banjarsari.desa.id', 'name' => 'banjarsari-banjarsari.desa.id', 'author' => 'BANJARSARI-BANJARSARI'],
            ['url' => 'https://sindanghayu.desa.id', 'name' => 'sindanghayu.desa.id', 'author' => 'SINDANGHAYU'],
            ['url' => 'https://sindangasih-banjarsari.desa.id', 'name' => 'sindangasih-banjarsari.desa.id', 'author' => 'SINDANGASIH-BANJARSARI'],
            ['url' => 'https://sindangsari-banjarsari.desa.id', 'name' => 'sindangsari-banjarsari.desa.id', 'author' => 'SINDANGSARI-BANJARSARI'],
            ['url' => 'https://ciherang-banjarsari.desa.id', 'name' => 'ciherang-banjarsari.desa.id', 'author' => 'CIHERANG-BANJARSARI'],
            ['url' => 'https://purwasari-banjarsari.desa.id', 'name' => 'purwasari-banjarsari.desa.id', 'author' => 'PURWASARI-BANJARSARI'],
            ['url' => 'https://ratawangi.desa.id', 'name' => 'ratawangi.desa.id', 'author' => 'RATAWANGI'],
            ['url' => 'https://ciulu.desa.id', 'name' => 'ciulu.desa.id', 'author' => 'CIULU'],
            ['url' => 'https://pamarican-pamarican.desa.id', 'name' => 'pamarican-pamarican.desa.id', 'author' => 'PAMARICAN-PAMARICAN'],
            ['url' => 'https://sidamulih.desa.id', 'name' => 'sidamulih.desa.id', 'author' => 'SIDAMULIH'],
            ['url' => 'https://sukamukti-pamarican.desa.id', 'name' => 'sukamukti-pamarican.desa.id', 'author' => 'SUKAMUKTI-PAMARICAN'],
            ['url' => 'https://sukajadi-pamarican.desa.id', 'name' => 'sukajadi-pamarican.desa.id', 'author' => 'SUKAJADI-PAMARICAN'],
            ['url' => 'https://sidaharja.desa.id', 'name' => 'sidaharja.desa.id', 'author' => 'SIDAHARJA'],
            ['url' => 'https://bangunsari-pamarican.desa.id', 'name' => 'bangunsari-pamarican.desa.id', 'author' => 'BANGUNSARI-PAMARICAN'],
            ['url' => 'https://neglasari-pamarican.desa.id', 'name' => 'neglasari-pamarican.desa.id', 'author' => 'NEGLASARI-CIAMIS'],
            ['url' => 'https://bantarsari.desa.id', 'name' => 'bantarsari.desa.id', 'author' => 'BANTARSARI'],
            ['url' => 'https://margajaya-ciamis.desa.id', 'name' => 'margajaya-ciamis.desa.id', 'author' => 'MARGAJAYA-CIAMIS'],
            ['url' => 'https://sukahurip.desa.id', 'name' => 'sukahurip.desa.id', 'author' => 'Desa Sukahurip'],
            ['url' => 'https://pasirnagara-pmrc.desa.id', 'name' => 'pasirnagara-pmrc.desa.id', 'author' => 'PASIRNAGARA-PMRC'],
            ['url' => 'https://cimaragas.desa.id', 'name' => 'cimaragas.desa.id', 'author' => 'CIMARAGAS'],
            ['url' => 'https://beber.desa.id', 'name' => 'beber.desa.id', 'author' => 'BEBER'],
            ['url' => 'https://raksabaya.desa.id', 'name' => 'raksabaya.desa.id', 'author' => 'RAKSABAYA'],
            ['url' => 'https://bojongmalang.desa.id', 'name' => 'bojongmalang.desa.id', 'author' => 'BOJONGMALANG'],
            ['url' => 'https://jayaraksa.desa.id', 'name' => 'jayaraksa.desa.id', 'author' => 'JAYARAKSA'],
            ['url' => 'https://cisaga.desa.id', 'name' => 'cisaga.desa.id', 'author' => 'CISAGA'],
            ['url' => 'https://sidamulya-cisaga.desa.id', 'name' => 'sidamulya-cisaga.desa.id', 'author' => 'SIDAMULYA-CISAGA'],
            ['url' => 'https://kepel-cisaga.desa.id', 'name' => 'kepel-cisaga.desa.id', 'author' => 'KEPEL-CISAGA'],
            ['url' => 'https://wangunjaya-cisaga.desa.id', 'name' => 'wangunjaya-cisaga.desa.id', 'author' => 'WANGUNJAYA-CISAGA'],
            ['url' => 'https://sukahurip-cisaga.desa.id', 'name' => 'sukahurip-cisaga.desa.id', 'author' => 'SUKAHURIP-CISAGA'],
            ['url' => 'https://bangunharja.desa.id', 'name' => 'bangunharja.desa.id', 'author' => 'BANGUNHARJA'],
            ['url' => 'https://tanjungjaya-cisaga.desa.id', 'name' => 'tanjungjaya-cisaga.desa.id', 'author' => 'TANJUNGJAYA-CISAGA'],
            ['url' => 'https://mekarmukti-cisaga.desa.id', 'name' => 'mekarmukti-cisaga.desa.id', 'author' => 'MEKARMUKTI-CISAGA'],
            ['url' => 'https://danasari-cisaga.desa.id', 'name' => 'danasari-cisaga.desa.id', 'author' => 'DANASARI-CISAGA'],
            ['url' => 'https://girimukti-cisaga.desa.id', 'name' => 'girimukti-cisaga.desa.id', 'author' => 'GIRIMUKTI-CISAGA'],
            ['url' => 'https://karyamulya.desa.id', 'name' => 'karyamulya.desa.id', 'author' => 'KARYAMULYA'],
            ['url' => 'https://sindangkasih.desa.id', 'name' => 'sindangkasih.desa.id', 'author' => 'SINDANGKASIH'],
            ['url' => 'https://budiasih.desa.id', 'name' => 'budiasih.desa.id', 'author' => 'BUDIASIH'],
            ['url' => 'https://budiharja.desa.id', 'name' => 'budiharja.desa.id', 'author' => 'BUDIHARJA'],
            ['url' => 'https://sukaraja-sindangkasih.desa.id', 'name' => 'sukaraja-sindangkasih.desa.id', 'author' => 'SUKARAJA-SINDANGKASIH'],
            ['url' => 'https://sukamanah-sinkas.desa.id', 'name' => 'sukamanah-sinkas.desa.id', 'author' => 'SUKAMANAH-SINKAS'],
            ['url' => 'https://sukasenang-sindangkasih.desa.id', 'name' => 'sukasenang-sindangkasih.desa.id', 'author' => 'SUKASENANG-SINDANGKASIH'],
            ['url' => 'https://sukaresik-sindangkasih.desa.id', 'name' => 'sukaresik-sindangkasih.desa.id', 'author' => 'SUKARESIK-SINDANGKASIH'],
            ['url' => 'https://wanasigra.desa.id', 'name' => 'wanasigra.desa.id', 'author' => 'WANASIGRA'],
            ['url' => 'https://baregbeg.desa.id', 'name' => 'baregbeg.desa.id', 'author' => 'BAREGBEG'],
            ['url' => 'https://sukamaju-baregbeg.desa.id', 'name' => 'sukamaju-baregbeg.desa.id', 'author' => 'SUKAMAJU-BAREGBEG'],
            ['url' => 'https://saguling.desa.id', 'name' => 'saguling.desa.id', 'author' => 'SAGULING'],
            ['url' => 'https://petirhilir.desa.id', 'name' => 'petirhilir.desa.id', 'author' => 'PETIRHILIR'],
            ['url' => 'https://pusakanagara.desa.id', 'name' => 'pusakanagara.desa.id', 'author' => 'PUSAKANAGARA'],
            ['url' => 'https://jelat.desa.id', 'name' => 'jelat.desa.id', 'author' => 'JELAT'],
            ['url' => 'https://karangampel.desa.id', 'name' => 'karangampel.desa.id', 'author' => 'KARANGAMPEL'],
            ['url' => 'https://sukamulya-baregbeg.desa.id', 'name' => 'sukamulya-baregbeg.desa.id', 'author' => 'SUKAMULYA-BAREGBEG'],
            ['url' => 'https://sukamantri-sukamantri.desa.id', 'name' => 'sukamantri-sukamantri.desa.id', 'author' => 'SUKAMANTRI-SUKAMANTRI'],
            ['url' => 'https://tenggerraharja.desa.id', 'name' => 'tenggerraharja.desa.id', 'author' => 'TENGGERRAHARJA'],
            ['url' => 'https://cibeureum-ciamis.desa.id', 'name' => 'cibeureum-ciamis.desa.id', 'author' => 'CIBEUREUM-CIAMIS'],
            ['url' => 'https://sindanglaya-sukamantri.desa.id', 'name' => 'sindanglaya-sukamantri.desa.id', 'author' => 'SINDANGLAYA-SUKAMANTRI'],
            ['url' => 'https://mekarwangi-sukamantri.desa.id', 'name' => 'mekarwangi-sukamantri.desa.id', 'author' => 'MEKARWANGI-SUKAMANTRI'],
            ['url' => 'https://cikupa-lumbung.desa.id', 'name' => 'cikupa-lumbung.desa.id', 'author' => 'CIKUPA-LUMBUNG'],
            ['url' => 'https://sukaraharja-lumbung-ciamis.desa.id', 'name' => 'sukaraharja-lumbung-ciamis.desa.id', 'author' => 'SUKARAHARJA-LUMBUNG-CIAMIS'],
            ['url' => 'https://lumbung.desa.id', 'name' => 'lumbung.desa.id', 'author' => 'LUMBUNG'],
            ['url' => 'https://lumbungsari-ciamis.desa.id', 'name' => 'lumbungsari-ciamis.desa.id', 'author' => 'LUMBUNGSARI-CIAMIS'],
            ['url' => 'https://rawa.desa.id', 'name' => 'rawa.desa.id', 'author' => 'RAWA'],
            ['url' => 'https://bantardawa.desa.id', 'name' => 'bantardawa.desa.id', 'author' => 'BANTARDAWA'],
            ['url' => 'https://purwadadi-purwadadi.desa.id', 'name' => 'purwadadi-purwadadi.desa.id', 'author' => 'PURWADADI-PURWADADI'],
            ['url' => 'https://purwajaya-ciamis.desa.id', 'name' => 'purwajaya-ciamis.desa.id', 'author' => 'PURWAJAYA-CIAMIS'],
            ['url' => 'https://karangpaningal.desa.id', 'name' => 'karangpaningal.desa.id', 'author' => 'KARANGPANINGAL'],
            ['url' => 'https://sidarahayu.desa.id', 'name' => 'sidarahayu.desa.id', 'author' => 'SIDARAHAYU'],
            ['url' => 'https://padaringan.desa.id', 'name' => 'padaringan.desa.id', 'author' => 'PADARINGAN'],
            ['url' => 'https://pasirlawang.desa.id', 'name' => 'pasirlawang.desa.id', 'author' => 'PASIRLAWANG'],
            ['url' => 'https://kutawaringin-purwadadi.desa.id', 'name' => 'kutawaringin-purwadadi.desa.id', 'author' => 'KUTAWARINGIN-PURWADADI'],
            ['url' => 'https://sukamulya-purwadadi.desa.id', 'name' => 'sukamulya-purwadadi.desa.id', 'author' => 'SUKAMULYA-PURWADADI'],
            ['url' => 'https://pasawahan-banjaranyar.desa.id', 'name' => 'pasawahan-banjaranyar.desa.id', 'author' => 'PASAWAHAN-BANJARANYAR'],
            ['url' => 'https://banjaranyar-banjaranyar.desa.id', 'name' => 'banjaranyar-banjaranyar.desa.id', 'author' => 'BANJARANYAR-BANJARANYAR'],
            ['url' => 'https://langkapsari.desa.id', 'name' => 'langkapsari.desa.id', 'author' => 'LANGKAPSARI'],
            ['url' => 'https://kalijaya.desa.id', 'name' => 'kalijaya.desa.id', 'author' => 'KALIJAYA'],
            ['url' => 'https://cikupa-banjaranyar.desa.id', 'name' => 'cikupa-banjaranyar.desa.id', 'author' => 'CIKUPA-BANJARANYAR'],
            ['url' => 'https://karyamukti-ciamis.desa.id', 'name' => 'karyamukti-ciamis.desa.id', 'author' => 'KARYAMUKTI-CIAMIS'],
            ['url' => 'https://cigayam.desa.id', 'name' => 'cigayam.desa.id', 'author' => 'CIGAYAM'],
            ['url' => 'https://sindangrasa.desa.id', 'name' => 'sindangrasa.desa.id', 'author' => 'SINDANGRASA'],
            ['url' => 'https://tanjungsari-banjaranyar.desa.id', 'name' => 'tanjungsari-banjaranyar.desa.id', 'author' => 'TANJUNGSARI-BANJARANYAR'],
            ['url' => 'https://bapenda.ciamiskab.go.id', 'name' => 'bapenda.ciamiskab.go.id', 'author' => 'Badan Pendapatan Daerah'],
            ['url' => 'https://absensi-diskominfo.ciamiskab.go.id', 'name' => 'absensi-diskominfo.ciamiskab.go.id', 'author' => 'Dinas Komunikasi dan Informatika'],
            ['url' => 'https://helo.ciamiskab.go.id/', 'name' => 'helo.ciamiskab.go.id', 'author' => 'Helo Ciamis'],
            ['url' => 'https://silancar.ciamiskab.go.id/', 'name' => 'silancar.ciamiskab.go.id', 'author' => 'Disdukcapil'],
        ];

        foreach ($websites as $webData) {
            // Check if Organization (Author) exists
            $organization = Organization::firstOrCreate(
                ['name' => $webData['author']],
                [
                    'code' => strtoupper(substr(Str::slug($webData['author'], ''), 0, 40)).'-'.Str::random(5),
                    'category' => 'dinas',
                    'is_active' => true,
                ]
            );

            // Create Website linked to Organization and Default CI
            Website::updateOrCreate(
                ['url' => $webData['url']],
                [
                    'name' => $webData['name'],
                    'organization_id' => $organization->id,
                    'ci_id' => $defaultCi->id,
                    'check_interval_minutes' => 60,
                    'is_active' => true,
                    'current_status' => 'unknown',
                ]
            );
        }
    }
}
